### PR TITLE
Updates gradle and bintray versions

### PR DESCRIPTION
**Pull request by deiga**
* Updates gradle to version  4.1
* Updates bintray to version 0.50

### CODE REVIEW

**Comment by kittinunf** [comment]
You might want to run `./gradlew wrapper` and commit the changes as well.

**Comment by deiga** [comment]
@kittinunf done

**Comment by yoavst** [comment]
@deiga Can you rebase it with master and update gradle to 4.2?

**Comment by deiga** [comment]
@yoavst Rebased. After some head banging into wall I gave up on gradle 4.2 as it seems that android library plugin doesn't support it

**Comment by kittinunf** [comment]
👍 👍 👍

**Pull request merged**
