### PR TITLE
[fuel-jackson] Added custom mapper support.

### PR DESCRIPTION
**Pull request by guilherme-pohlmann**
## Description

Added support for user defined object mappers at fuel-jackson.

**Motivation**
I'm working on a layered spring boot web application following Domain Driven Design.
By default, our services communicate using snake case Json's, so at application startup, we create an object mapper and configure it to use snake case, along with other things. We use this mapper as a Bean, so we can inject it in other layers (like infra) and reuse the same behavior.
This change adds `customMapper` parameter to `responseObject` methods, so users (like us) can pass their own mappers.

**Important:**
I've renamed the property 'mapper' to 'defaultMapper', this can cause some applications to break if them are accessing this property. But I think this is very unlikely, and this property could even be internal or private. Please let me know your opinion.

## Type of change

Check all that apply

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (a change which changes the current internal or external interface)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Created the method `jacksonTestResponseSyncObjectWithCustomMapper` for custom mapper testing. I think the rest is pretty much covered. What do you think ?

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation, if necessary
- [x] My changes generate no new compiler warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Inspect the bytecode viewer, including reasoning why

### CODE REVIEW

**Comment by iNoles** [comment]
Can you added more Tests for this to make Codecov happy?

**Comment by guilherme-pohlmann** [comment]
@iNoles I increased test coverage but codecov still isn't happy. I can't see whats wrong. Dont' know why it's showing the files `HttClient.kt` and `FuelError.kt` 🤔 . Can you help me ?

**Comment by iNoles** [comment]
@guilherme-pohlmann As for now, you can ignored those files. I guess it not like inline functions, so it is fine.

**Comment by kittinunf** [comment]
I think this looks great for me. Can you also add a bit of document in the respective README file to tell everyone the behavior?

**Comment by SleeplessByte** [comment]
@guilherme-pohlmann I agree with @kittinunf: If you can add a bit of `README.md` in the jackson readme (not the main one), we'll be happy to merge this.

Thank you for the work!

**Comment by kittinunf** [comment]
@guilherme-pohlmann if you have time please 🙏

**Comment by guilherme-pohlmann** [comment]
@kittinunf  @SleeplessByte 

I added some documentation, what do you think? I'm sorry if you find any problem with my English, I'm from Brazil. :sweat_smile::sweat_smile:
Any problems let me know that I will be happy to fix it.

**Comment by kittinunf** [comment]
This looks splendid to me! I will approve this :) I am sure that @SleeplessByte is happy with this too!

**Comment by kittinunf** [comment]
Merge this!

**Pull request merged**
