### PR TITLE
Update 'Synchronous Call' documentation in README.

### PR DESCRIPTION
**Pull request by glureau**
Just lost 5 minutes searching the sync() method.
Do not hesitate to cancel this PR and improve the documentation on your side if you want to (it's just an easy-fix for you anyway).

### CODE REVIEW

**Comment by kittinunf** [comment]
Actually, we have 2 ways to force Fuel to be asynchronous.

First, use `sync()`, second use the `response()` method. Both are async

The difference is the former preserves interface to be a callback-ish kinda way but in synchronous mode, such as 

``` Kotlin
Fuel .... .sync().response { request, response, result ->
}
```

Meanwhile, the latter yields interface such as, 

``` Kotlin
val (request, response, data) = Fuel ... .response()
```

I am all in for adding/improving README, but you might wanna change things a bit to be perfectly accurate.

**Comment by yoavst** [comment]
Actually, I removed the `sync()` method for `response()`. 

For testing you can still use `Fuel.testMode {} `

**Comment by glureau** [comment]
Didn't see the "Blocking" section before!

**Comment by glureau** [comment]
Looks like https://github.com/kittinunf/Fuel/pull/61 already includes the modification.
Closing this PR.

**Pull request closed without merging**
