### PR TITLE
Fix upload boundary

### LINKED ISSUE #298: Got IndexOutOfBoundException when upload file
Fuel: `v1.12.0`

I got IndexOutOfBoundException when upload file which selected from Android gallery

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.get(ArrayList.java:437)
at com.github.kittinunf.fuel.core.requests.UploadTaskRequest.<init>(UploadTaskRequest.kt:63)
at com.github.kittinunf.fuel.core.Request$taskRequest$2.invoke(Request.kt:63)
at com.github.kittinunf.fuel.core.Request$taskRequest$2.invoke(Request.kt:23)
```

Here is my code

```kotlin
"files".httpUpload()
    .source { _, _ ->
        file // File from Android gallery
    }
    .name { file.name }
    .timeout(30000)
    .responseString { _, _, _ -> }
```

I checked that it cannot get boundary from `Content-Type`

```kotlin
private val boundary = request.headers["Content-Type"]?.split("=", limit = 2)?.get(1) ?: System.currentTimeMillis().toString(16)
```

### PR DESCRIPTION
**Pull request by babedev**
### What's in this PR?

This PR aims to fix #298.

### CODE REVIEW

**Comment by kittinunf** [comment]
Some tests please 🙏

**Comment by kittinunf** [comment]
This looks good to me. Can you please also add this to our showcase sample too? 

Looks great to me, merge as you are ready! 🚢 🇮🇹

**Comment by babedev** [comment]
Thank you. I will add some sample in Readme before merge this PR.

**Comment by kittinunf** [comment]
Thanks, @babedev. I will release the next version to fix this issue so you can benefit of this in your project. 👍

**Comment by kittinunf** [comment]
Merging in?

**Comment by babedev** [comment]
Ah... Forgot to edit README. I will merge right away.

**Pull request merged**
