### PR TITLE
[Release] New Version 1.16.0

### PR DESCRIPTION
**Pull request by kittinunf**
## Description

This PR aims to release Fuel new version 1.16.0. This will target Kotlin 1.3 with new coroutine.

## Type of change

Check all that apply

- [x] Release new version

## Checklist:

- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Maybe we can include @markGilchrist work on suspending client?

**Comment by kittinunf** [comment]
Okay I will correct that.

**Comment by markGilchrist** [comment]
@kittinunf  @SleeplessByte please credit all the others who helped me with this pr when I was stuck/in need of inspiration. @lucasvalenteds @iNoles

**Comment by kittinunf** [comment]
Rebase against latest master with @markGilchrist PR!

**Comment by clarcharr** [comment]
So I mentioned in the original PR, but this release bumps the Kotlin language version up to 1.3, making the coroutines completely incompatible with 1.2. I don't actually see a good reason for this, considering how 1.3 isn't stable yet, even though it's getting very close. This release should probably still rely on 1.2, and then an additional release can be made once 1.3 is stabilised to migrate, considering how most of the migration is completely automatic.

**Comment by NikkyAI** [comment]
i'd really like to use 1.3 in my program and I'd hate to move away from fuel for networking or be forced to fork my own coroutine support

the release better be marked as `-rc13` or similar though to make sure people do not get surprised by accidentally updating

**Comment by clarcharr** [comment]
Personally, I'd recommend doing what the coroutines library itself does: `0.16.0` should be released with 1.2 support, while `0.16.0-eap13` is on 1.3. This is a greater maintenance burden but it won't be by much.

**Comment by markGilchrist** [comment]
@kittinunf

I would like to use kotlin 1.3 in my own project so I am understand @NikkyAI point of view but I can see what @clarcharr is getting at

I wonder, is there a middle ground where we make a `release-v1.16.0` without my pr and a   `release-v1.16.0-1.3` version with it?

**Comment by NikkyAI** [comment]
maybe add a `1.2` branch that gets features backported until 1.3 is out and stable, i do not see a way to support coroutines for both without multiple modules in the same branch easily

**Comment by iNoles** [comment]
@clarcharr you also forgot kotlin serialization

**Comment by NikkyAI** [comment]
even jetbrains is not consistent with what the eap / rc suffix is, so i think as long as there is one it is clear to users
i prefer `-rc13` or `-rc3` or `rc13-3`

because it is the third rc on 1.3 (if i did not screw up counting)

**Comment by kittinunf** [comment]
@clarcharr but my understanding is that without @markGilchrist's PR in #438, coroutine extension is a bit buggy and not even worth upgrading? So you can just stay on `v1.15.0`? (I would love to hear this before making the following)

It is a burden but I would love to accommodate everyone's request. I will make another release targeting Kotlin 1.2.71 and lower Coroutine version requirement.

So, I will do the following 

`1.16.0` will support Kotlin `1.3-rc`
`1.15.1` will support Kotlin `1.2.71` and coroutine `0.23.3`

How does this sound to you?

**Comment by clarcharr** [comment]
I really appreciate it, @kittinunf! This sounds good to me.

**Comment by kittinunf** [comment]
Just updated README, hopefully, everyone is happy 🎉 ❤️ !

**Comment by kittinunf** [comment]
I am merging this in ....

**Pull request merged**
