### PR TITLE
Feature/json body

### PR DESCRIPTION
**Pull request by pawin**

### CODE REVIEW

**Comment by yoavst** [comment]
but what if we want to use another content type?

**Comment by pawin** [comment]
I'm finding how to create enum with custom value, is it possible to do that?

**Comment by kittinunf** [comment]
I think It is impossible to cover all the case as `Content-Type` can be just about anything.

http://greenbytes.de/tech/webdav/draft-ietf-httpbis-p2-semantics-26.html#header.content-type

After careful consideration, we have to tackle this in [Encoding](https://github.com/kittinunf/Fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Encoding.kt) class instead. We need a enum to specify how we encode the parameters.

**Comment by yoavst** [comment]
It can be implemented as Interceptor.

**Pull request closed without merging**
