### PR TITLE
Move JSONObject into a new Module

### PR DESCRIPTION
**Pull request by iNoles**
## Description

Moving JSON related files into a new Module 

## Type of change

Check all that apply

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactoring (a change which changes the current internal or external interface)
- [ ] This change requires a documentation update

## How Has This Been Tested?

In case you did not include tests describe why you and how you have verified the
changes, with instructions so we can reproduce. If you have added comprehensive
tests for your changes, you may omit this section.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation, if necessary
- [x] My changes generate no new compiler warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Inspect the bytecode viewer, including reasoning why

### CODE REVIEW

**Comment by kittinunf** [comment]
The test fails with this though

```
e: /home/travis/build/kittinunf/Fuel/fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/RequestAndroidAsyncTest.kt: (5, 42): Unresolved reference: core
e: /home/travis/build/kittinunf/Fuel/fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/RequestAndroidAsyncTest.kt: (6, 42): Unresolved reference: extension
e: /home/travis/build/kittinunf/Fuel/fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/RequestAndroidAsyncTest.kt: (126, 43): Unresolved reference: responseJson
e: /home/travis/build/kittinunf/Fuel/fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/RequestAndroidAsyncTest.kt: (126, 58): Cannot infer a type for this parameter. Please specify it explicitly.
e: /home/travis/build/kittinunf/Fuel/fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/RequestAndroidAsyncTest.kt: (126, 63): Cannot infer a type for this parameter. Please specify it explicitly.
e: /home/travis/build/kittinunf/Fuel/fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/RequestAndroidAsyncTest.kt: (126, 68): Cannot infer a type for this parameter. Please specify it explicitly.
```

**Comment by iNoles** [comment]
I will fix that later on the day.

**Comment by iNoles** [comment]
Looks like I needed to add more Tests. :|

**Comment by kittinunf** [comment]
I don't see anything wrong with this PR? Shall we merge?

**Pull request merged**
