### PR TITLE
[fuel-coroutines] improve exception handling testing

### LINKED ISSUE #538: [fuel-coroutines] not all exceptions are properly wrapped as FuelError
# Bug Report

## Description

some Exceptions thrown inside a suspending request are not wrapped into FuelError

## To Reproduce
cause a ConnectException on a suspending request with eg. `awaitStringResponse`
it will not be wrapped in a Fuel Error and crash the test

```Kotlin
@Test
fun handleConnectException() = runBlocking {
    val (_, res, result) = Fuel.get("http://127.0.0.1:80")
        .awaitStringResponse()

    assertThat(res, notNullValue())
    assertThat(result, notNullValue())
    assertThat(result.component2(), notNullValue())
    val success = when (result) {
        is Result.Success -> true
        is Result.Failure -> false
    }
    assertFalse("should catch exception", success)
    when (result) {
        is Result.Success -> fail("should catch connect exception")
        is Result.Failure -> {
            assertThat(
                result.error.exception as? ConnectException,
                isA(ConnectException::class.java)
            )
        }
    }
}
```

## Expected behavior

should handle it in FuelError like non-suspending requests

### PR DESCRIPTION
**Pull request by NikkyAI**
## Description

adds #538 as test to avoid regression in exception handling 

## Type of change

Check all that apply

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (a change which changes the current internal or external interface)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation, if necessary
- [ ] My changes generate no new compiler warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Inspect the bytecode viewer, including reasoning why

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Rebase on #512. I think this is already fixed

**Comment by NikkyAI** [comment]
in case 512 fixes it.. i will just add the test

**Comment by SleeplessByte** [comment]
Rebase on master, it's merged :dagger:

**Comment by NikkyAI** [comment]
fixed by #512 
so this will just add the test to avoid regression

**Comment by SleeplessByte** [comment]
Great!

**Pull request merged**
