### PR TITLE
Fuel's module fuel-andorid don't have Result's depend

### PR DESCRIPTION
**Pull request by shaomaicheng**
add compile 'com.github.kittinunf.result:result:1.2.0' in fuel-andorid's gradle

### CODE REVIEW

**Comment by shaomaicheng** [comment]
why？some people can not build this project...

**Comment by yoavst** [comment]
But `fuel-android` depends on `fuel` which depends on `result`

**Comment by kittinunf** [comment]
I don't think that we need to explicitly add `Result` into the dependency list. Can you explain more @shaomaicheng ?

**Comment by kittinunf** [comment]
I'm closing this

**Comment by leus** [comment]
Using maven:
```
		<dependency>
			<groupId>com.github.kittinunf.fuel</groupId>
			<artifactId>fuel</artifactId>
			<version>1.8.0</version>
		</dependency>

```
I don't see any library or jar containing a `Result` class. Where is this class located?

**Pull request closed without merging**
