### PR TITLE
⬆ [Release] Version 2.2.0

### PR DESCRIPTION
**Pull request by kittinunf**
## Description

This will release fuel's new version!

### Changes

- Cleanup HttpClient #639 by @iNoles  

- Catch Forge's MissingAttributeError on FuelError #661 by @iNoles

- Fix content length parameter for InlineDataPart #653 by @ASKabanets

- Flesh out Quick Start examples #654 by @mbidewell 

- :sparkles: Add support for custom Gson instances #645 by @lostintime

- Correct RxFuel api surface #640 by @kittinunf

## Type of change

Check all that apply

- [x] New version - 2.2.0

## How Has This Been Tested?

In case you did not include tests describe why you and how you have verified the
changes, with instructions so we can reproduce. If you have added comprehensive
tests for your changes, you may omit this section.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation, if necessary
- [ ] My changes generate no new compiler warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Inspect the bytecode viewer, including reasoning why

### CODE REVIEW

**Comment by NikkyAI** [comment]
did you create the PR incorrectly, none of the changres that are described are there?

**Comment by kittinunf** [comment]
@NikkyAI 🤔 Could you explain more on that? You don't see the changes because all of the changes have been merged to master, no? This PR is just bumping version from the previous version, no?

**Comment by SleeplessByte** [comment]
I agree with @NikkyAI that it _could_ be much clearer if we start to work with a `master` and a `develop` branch (in that case all changes would be visible when creating a PR on `release/xxx` from `develop` to `master`; but this should be OK.

Perhaps we start keeping a CHANGELOG.md, and whenever we merge, we add a line to `unreleased` section in that changelog. That way, when we release, it's just replacing the `unreleased` header with the new version, and you can be certain that the changes are on master!

**Comment by kittinunf** [comment]
@SleeplessByte @NikkyAI alright! Let's do this? I will create develop branch then?

**Pull request merged**
