### PR TITLE
[3.x] Add more tests and expose interface for singleton

### PR DESCRIPTION
**Pull request by kittinunf**
### What's in this PR?

Add more tests and expose the interface for the client of singleton to use.

### CODE REVIEW

**Comment by iNoles** [comment]
Oh, I didn't added test for this folder before.

**Comment by kittinunf** [comment]
But do you know it says that we don't have tests covered? Since we are adding tests for the interface in this PR?

**Comment by iNoles** [comment]
> But do you know it says that we don't have tests covered? Since we are adding tests for the interface in this PR?

Suspend one. Well, I wouldn't worried about it.

**Comment by kittinunf** [comment]
Yeah, but I have added here, right? 

https://github.com/kittinunf/fuel/pull/798/files#diff-da6ed83027be159e12093e620ff4f9447224d1608222b97dcdda9b1b4a4d4631R29-R50

**Comment by iNoles** [comment]
Hmm, don't brother to add suspend test on this one. How about we closed this one to merge with my own?

**Comment by kittinunf** [comment]
Ok close this PR then.

**Pull request closed without merging**
