### PR TITLE
Add PATCH method for Fuel

### LINKED ISSUE #133: Missing PATCH-Verb
Is there a possibility to issue PATCH-requests without using the semi-standard `X-HTTP-Method-Override` header, e.g. `Fuel.patch(...)`?

Maybe I'm just not seeing it, there is a patch method defined [here](https://github.com/kittinunf/Fuel/blob/5ce5955b34a2f237ed3b3c223415da74619ad4ab/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Method.kt#L8) but it's not exposed like GET, POST, PUT or DELETE. Is there a reason for this?

### PR DESCRIPTION
**Pull request by kittinunf**
### What's in this PR?

This PR mitigates the issue where Fuel don't expose PATCH method for client to use. This PR will remedy that.

Merging this should close #133

### CODE REVIEW

**Comment by babedev** [comment]
Something wrong with tests?

**Comment by kittinunf** [comment]
It seems like httpbin.org doesn't support POST method for httpbin.org/patch endpoint.

**Comment by kittinunf** [comment]
🎉 🎉 🎉

**Comment by babedev** [comment]
Wow, let's merge this.

**Pull request merged**
