### PR TITLE
Basic Circle CI Support

### PR DESCRIPTION
**Pull request by iNoles**
## Description

Circle CI is much better than Travis CI . Bear with me, I don't have a lot of experience to work with Circle CI before. It will take multiple commits to get it fully working. 

## Type of change

Check all that apply

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactoring (a change which changes the current internal or external interface)
- [ ] This change requires a documentation update

## How Has This Been Tested?

In case you did not include tests describe why you and how you have verified the
changes, with instructions so we can reproduce. If you have added comprehensive
tests for your changes, you may omit this section.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation, if necessary
- [ ] My changes generate no new compiler warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Inspect the bytecode viewer, including reasoning why

### CODE REVIEW

**Comment by SleeplessByte** [comment]
LGTM so far! Any issues you're having? Or do you want to have this merged and then we just run it on BOTH until we switch fully

**Comment by iNoles** [comment]
I never have circle ci before. I would like to test it out.

**Comment by kittinunf** [comment]
Maybe let's merge then? Unless you wanna add somethign more on this?

**Comment by iNoles** [comment]
I am planning to add more on testing the configuration out in circle ci.

**Comment by iNoles** [comment]
Since this PR is created before the circleci checks, I think it is best to merge it now then add more later.

**Pull request merged**
