### PR TITLE
Issue 102 added test to verify behaviour is correct

### PR DESCRIPTION
**Pull request by markGilchrist**
written test that currently passes, I feel that appropiate behaviour is already implmented

### CODE REVIEW

**Comment by kittinunf** [comment]
🤔 Which behavior do you try to write the test for though?

**Comment by markGilchrist** [comment]
@kittinunf The tests recreates the behaviour raised in the issue, hence we get a  junction in the roads, as I see it

if the current behaviour is what we want, (handled as a fuel exception, which I think is correct) then we can either junk this pr as superfluous 

or we decided this is not the desired behaviour and we change the test and implement changes.

as ever I am here to do whatever you ask!

**Comment by kittinunf** [comment]
Ah I see. Understood now. Sorry just need a bit more info. Approved!

**Comment by kittinunf** [comment]
I will merge on your behalf. :)

**Pull request merged**
