### PR TITLE
Support json array

### PR DESCRIPTION
**Pull request by kittinunf**
To support JsonArray as root object of response.

### CODE REVIEW

**Comment by kittinunf** [comment]
@yoavst Can you help me review this?

**Comment by kittinunf** [comment]
OK, thank you. I will merge this in.

**Comment by ismail-s** [comment]
I literally was just about to create a PR to add this... (though not in the way you did)

**Comment by kittinunf** [comment]
Can you elaborate more (on the way you were about to propose)? I'm happy to discuss/change if there is a better way.

**Comment by ismail-s** [comment]
No, no, your way is better. I was going to add rsponseJsonArray methods.

**Comment by ismail-s** [comment]
I just found it really coincidental that you had just merged it as I thought about it.

**Comment by kittinunf** [comment]
Alrighty, thanks anyway. I hope you like using Fuel. :)

**Pull request merged**
