### PR TITLE
Improve Gson Coverages

### PR DESCRIPTION
**Pull request by iNoles**
Thank you for submitting your Pull Request. Please make sure you have
familiarised yourself with the [Contributing Guidelines](https://github.com/kittunf/Fuel/CONTRIBUTING.md)
before continuing.

## Description

Include a summary of the change and which [issue](https://github.com/kittunf/Fuel/issues)
this fixes. Also include relevant motivation and context. List any dependencies
that are required for this change and why they are necessary.

Fixes #0
Fixes #0

## Type of change

Check all that apply

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (change which changes the current internal or external interface)
- [ ] This change requires a documentation update

## How Has This Been Tested?

In case you did not include tests describe why you and how you have verified the
changes, with instructions so we can reproduce. If you have added comprehensive
tests for your changes, you may ommit this section.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation, if necessary
- [x] My changes generate no new compiler warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Why is this breaking, and what's up with codecov? It's not reporting any change.

**Comment by iNoles** [comment]
@SleeplessByte i think it is started on master@f373c1f

**Comment by SleeplessByte** [comment]
@kittinunf merge if okay, but note that it is breaking change.

**Comment by kittinunf** [comment]
I am okay to have this merge. Even though I am using Gson in my project. I have never used `gsonDeserializerOf` at all. I am not sure about others but I guess we can note that in the next release.

**Pull request merged**
