### PR TITLE
Possible IllegalStateException

### PR DESCRIPTION
**Pull request by dmitry-zhuravlev**
fix possible IllegalStateException in case connection.responseMessage==null

### CODE REVIEW

**Comment by dmitry-zhuravlev** [comment]
Squashed to the one commit.

**Comment by kittinunf** [comment]
Nice!

**Comment by kittinunf** [comment]
Hmm, do you know why sudden your changes become larger? Now it is 10 files.

**Comment by dmitry-zhuravlev** [comment]
Indeed wasn't merged for some reason. Thanks for point me out!
Now it contains only one file with the needed change.

**Comment by kittinunf** [comment]
Thanks! I am merging this in.

**Pull request merged**
