### PR TITLE
Added ReadTimeout into documentation

### PR DESCRIPTION
**Pull request by carmas123**

### CODE REVIEW

**Comment by kittinunf** [comment]
You might wanna rebase master again, as #87 is merged already.

**Comment by carmas123** [comment]
I don't know how can I do that...I'm not practiced with GitHub :( sorry

**Comment by yoavst** [comment]
Well, I'm also not so practiced with git, so I can't help in this :(
I can add it to README by myself if it is OK.

**Comment by kittinunf** [comment]
Common. Just update your fork. Then, rebase your branch. 

Update;
https://help.github.com/articles/syncing-a-fork/ 

Rebase
`git rebase origin master`

**Comment by carmas123** [comment]
@yoavst please you can do that?

**Comment by carmas123** [comment]
@kittinunf I use directlly Git in Android studio

**Comment by yoavst** [comment]
@carmas123 Try to do what @kittinunf has said. comment here if you fails.

**Comment by carmas123** [comment]
Now is good?

**Comment by kittinunf** [comment]
No. b2211ff should not be in changes.

**Comment by kittinunf** [comment]
If you don't mind, I can update README.md for you.

**Comment by carmas123** [comment]
Please thank you

**Pull request closed without merging**
